### ISSUE TITLE
Error during export and missing units setting 

### ISSUE THREAD

**Issue by shiftycats** [DarklightGames/io_scene_ase#2]
Blender version: 2.93.1

Plugin throws an error during export. The "Meters/Unreal" setting has disappeared from the UI as well:

![exporter-settings](https://user-images.githubusercontent.com/36604408/130125210-b5c73ef4-a72a-41bd-a182-8c3c4800c466.png)

### Replication steps
Select mesh object > Hit `Export ASE` in the exporter window.

### Log
```
Python: Traceback (most recent call last):
  File "C:\Users\fooly\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_ase\exporter.py", line 39, in execute
    options.scale = self.units_scale[self.units]
KeyError: <_PropertyDeferred, <built-in function EnumProperty>, {'items': (('M', 'Meters', ''), ('U', 'Unreal', '')), 'name': 'Units'}>

location: <unknown location>:-1
```

**Comment by cmbasnett** [comment]
Fixed in 1.0.2.
