### ISSUE TITLE
AutoSmooth shading by degrees doesnt work

### ISSUE THREAD

**Issue by DanielMoravek** [DarklightGames/io_scene_ase#3]
Using Blenders Autosmooth for a mesh doesnt seems to work on exported meshes (tested in UT3 Ed).
Imported mesh appears to have full smooth shading.

Only manually specified hard edges (Mark Sharp) works on exported mesh.

![AutosmoothSettings](https://user-images.githubusercontent.com/39673731/155856751-d2a806f8-50e4-4773-bded-26a720b11401.jpg)

![UT3EdAutosmoothDontWork](https://user-images.githubusercontent.com/39673731/155857011-aa8ad19e-4866-4a8c-96f0-9f84a3014a5a.jpg)

**Comment by cmbasnett** [comment]
This is now fixed in version 1.2.0.
