### ISSUE TITLE
How can I export mesh as collision only? (yellow lines)

### ISSUE THREAD

**Issue by uzublecker** [DarklightGames/io_scene_ase#5]
Hello

I'd like to know if there's a way to export any mesh as collision only. I'm using more than 1K Triangles. so for a fluid gameplay inside an old engine I'll put them with no colission. Is it possible to export any mesh as collision only?

Thanks for this bud! really helpful

**Comment by cmbasnett** [comment]
I don't think it is possible to have a collision-only mesh. My suggestion would be to just have an infinitesimally small piece of geo so that it has *something*.
